CREATE TABLE IF NOT EXISTS usuarios (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  senha VARCHAR(255) NOT NULL,
  perfil VARCHAR(50) NOT NULL,
  setor VARCHAR(100) NOT NULL DEFAULT '',
  cargo VARCHAR(100) NOT NULL DEFAULT '',
  lider_id INT REFERENCES usuarios(id) ON DELETE SET NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categorias (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mips (
  id SERIAL PRIMARY KEY,
  codigo VARCHAR(20) UNIQUE NOT NULL,
  titulo VARCHAR(255) NOT NULL,
  resumo TEXT,
  objetivo TEXT,
  conteudo TEXT NOT NULL,
  status VARCHAR(50) DEFAULT 'Em Revisão',
  orientacao_correcao TEXT DEFAULT '',
  autor_id INT REFERENCES usuarios(id) ON DELETE SET NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS mip_versoes (
  id SERIAL PRIMARY KEY,
  mip_id INT NOT NULL REFERENCES mips(id) ON DELETE CASCADE,
  codigo VARCHAR(20) NOT NULL,
  titulo VARCHAR(255) NOT NULL,
  resumo TEXT,
  objetivo TEXT,
  conteudo TEXT NOT NULL,
  status VARCHAR(50) NOT NULL,
  alterado_por INT REFERENCES usuarios(id) ON DELETE SET NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS receita_versoes (
  id SERIAL PRIMARY KEY,
  receita_id INT NOT NULL REFERENCES receitas(id) ON DELETE CASCADE,
  titulo VARCHAR(255) NOT NULL,
  rendimento_base INT NOT NULL,
  ingredientes JSONB NOT NULL,
  alterado_por INT REFERENCES usuarios(id) ON DELETE SET NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS perguntas_avaliacao (
  id SERIAL PRIMARY KEY,
  titulo VARCHAR(120) NOT NULL,
  pergunta TEXT NOT NULL,
  criterios JSONB NOT NULL DEFAULT '[]',
  obrigatoria BOOLEAN NOT NULL DEFAULT FALSE,
  ordem INT NOT NULL DEFAULT 0,
  ativa BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS avaliacoes (
  id SERIAL PRIMARY KEY,
  usuario_avaliado_id INT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  mes_referencia CHAR(7) NOT NULL,
  elaborado_por VARCHAR(150) NOT NULL,
  aplicado_por VARCHAR(150) NOT NULL,
  pontuacao_total INT NOT NULL,
  percentual INT NOT NULL,
  classificacao VARCHAR(20) NOT NULL,
  respostas JSONB NOT NULL,
  token_compartilhamento VARCHAR(64) UNIQUE NOT NULL,
  criado_por INT REFERENCES usuarios(id) ON DELETE SET NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (usuario_avaliado_id, mes_referencia)
);

CREATE INDEX IF NOT EXISTS avaliacoes_usuario_mes_idx
  ON avaliacoes (usuario_avaliado_id, mes_referencia DESC);

CREATE TABLE IF NOT EXISTS clientes_reclamacao (id SERIAL PRIMARY KEY,nome VARCHAR(180) UNIQUE NOT NULL,ativo BOOLEAN NOT NULL DEFAULT TRUE,criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tipos_reclamacao (id SERIAL PRIMARY KEY,nome VARCHAR(150) UNIQUE NOT NULL,ativo BOOLEAN NOT NULL DEFAULT TRUE,criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS reclamacoes (id SERIAL PRIMARY KEY,cliente_id INT NOT NULL REFERENCES clientes_reclamacao(id),assunto VARCHAR(220) DEFAULT '',tipo_id INT NOT NULL REFERENCES tipos_reclamacao(id),lider_responsavel_id INT NOT NULL REFERENCES usuarios(id),descricao TEXT NOT NULL,anexos JSONB NOT NULL DEFAULT '[]'::jsonb,criado_por INT REFERENCES usuarios(id) ON DELETE SET NULL,criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS categorias_acesso (id SERIAL PRIMARY KEY,nome VARCHAR(100) UNIQUE NOT NULL,permissoes JSONB NOT NULL DEFAULT '[]'::jsonb,ativo BOOLEAN NOT NULL DEFAULT TRUE,criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS categoria_acesso_id INT REFERENCES categorias_acesso(id) ON DELETE SET NULL;
