import { useEffect, useState } from 'react';
import axios from 'axios';
import { BarChart3, CheckCircle2, Clock3, Image, Paperclip, Plus, RotateCcw, Trash2, X } from 'lucide-react';
import Sidebar from '../components/Sidebar';
import LeitorTopbar from '../components/LeitorTopbar';

const cores={verde:{nome:'Não urgente',cor:'#15803d',fundo:'#dcfce7'},amarelo:{nome:'Média',cor:'#a16207',fundo:'#fef9c3'},vermelho:{nome:'Imediata',cor:'#b91c1c',fundo:'#fee2e2'}};
const ehImagem=a=>String(a.tipo||'').startsWith('image/')||/\.(png|jpe?g|gif|webp)$/i.test(a.url||'');
const formatarPrazo=min=>min>=60&&min%60===0?`${min/60} hora${min/60===1?'':'s'}`:`${min} minutos`;
const restante=(fim,agora)=>{const ms=new Date(fim)-agora,atrasado=ms<0,total=Math.abs(ms),h=Math.floor(total/3600000),m=Math.floor((total%3600000)/60000);return{atrasado,texto:`${h}h ${String(m).padStart(2,'0')}min`};};

export default function Reclamacoes(){
  const api=`http://${window.location.hostname}:7001/api`,user=JSON.parse(localStorage.getItem('user')||'{}'),perfil=user.perfil?.toLowerCase(),headers={Authorization:`Bearer ${localStorage.getItem('token')}`};
  const podeRegistrar=['administrador','editor','gerente'].includes(perfil)||(user.permissoes||[]).includes('reclamacoes.registrar');
  const [catalogos,setCatalogos]=useState({clientes:[],tipos:[],lideres:[],prazos:{prazo_verde_min:1440,prazo_amarelo_min:180,prazo_vermelho_min:60}}),[metricas,setMetricas]=useState({por_tipo:[],por_lider:[],por_mes:[],por_cliente:[],por_prioridade:[]});
  const [itens,setItens]=useState([]),[formAberto,setFormAberto]=useState(false),[salvando,setSalvando]=useState(false),[foto,setFoto]=useState(null),[agora,setAgora]=useState(new Date()),[filtro,setFiltro]=useState('todos');
  const [form,setForm]=useState({cliente_id:'',cliente_busca:'',tipo_id:'',tipo_busca:'',lider_responsavel_id:'',descricao:'',anexos:[],prioridade:'verde'});
  async function carregar(){const chamadas=[axios.get(`${api}/reclamacoes/catalogos`,{headers}),axios.get(`${api}/reclamacoes/metricas`,{headers})];if(podeRegistrar)chamadas.push(axios.get(`${api}/reclamacoes`,{headers}));const[c,m,r]=await Promise.all(chamadas);setCatalogos(c.data);setMetricas(m.data);if(r)setItens(r.data);}
  useEffect(()=>{carregar().catch(()=>{});const i=setInterval(()=>setAgora(new Date()),30000);return()=>clearInterval(i);},[]);
  async function anexar(arquivos){const novos=[];for(const arquivo of [...arquivos].slice(0,10-form.anexos.length)){const dados=new FormData();dados.append('image',arquivo);const r=await axios.post(`${api}/upload`,dados,{headers});novos.push({nome:arquivo.name,url:r.data.url,tipo:arquivo.type});}setForm(v=>({...v,anexos:[...v.anexos,...novos]}));}
  async function salvar(e){e.preventDefault();setSalvando(true);try{await axios.post(`${api}/reclamacoes`,form,{headers});setForm({cliente_id:'',cliente_busca:'',tipo_id:'',tipo_busca:'',lider_responsavel_id:'',descricao:'',anexos:[],prioridade:'verde'});setFormAberto(false);await carregar();}catch(err){alert(err.response?.data?.error||'Erro ao registrar reclamação.');}finally{setSalvando(false);}}
  async function mudarStatus(id,status){try{await axios.put(`${api}/reclamacoes/${id}/status`,{status},{headers});await carregar();}catch(err){alert(err.response?.data?.error||'Não foi possível concluir a reclamação.');}}
  async function excluir(id){if(confirm('Excluir definitivamente esta reclamação?')){await axios.delete(`${api}/reclamacoes/${id}`,{headers});carregar();}}
  const maior=lista=>Math.max(1,...lista.map(x=>x.total)),visiveis=itens.filter(x=>filtro==='todos'||x.status===filtro);
  const Barras=({dados,prioridade=false})=><div className="space-y-3">{dados.map(x=><div key={x.nome}><div className="flex justify-between gap-3 text-sm mb-1"><span className="truncate">{cores[x.nome]?.nome||x.nome}</span><strong>{x.total}</strong></div><div className="h-3 bg-[var(--bg-main)] rounded-full overflow-hidden"><div className="h-full rounded-full" style={{width:`${x.total/maior(dados)*100}%`,background:prioridade?(cores[x.nome]?.cor||'#a65526'):'#d97706'}}/></div></div>)}{!dados.length&&<p className="text-[var(--text-muted)]">Sem dados.</p>}</div>;
  const conteudo=<main className="flex-1 p-4 sm:p-8 max-w-[1500px] w-full mx-auto"><header className="flex flex-col sm:flex-row justify-between gap-4 mb-7"><div><p className="section-label">Qualidade e atendimento</p><h1 className="text-3xl font-bold">Reclamações</h1><p className="text-[var(--text-muted)]">Prazos, ocorrências e indicadores de atendimento.</p></div>{podeRegistrar&&<button onClick={()=>setFormAberto(true)} className="bg-[var(--primary)] text-white px-5 py-3 rounded-xl font-bold flex items-center h-fit"><Plus className="mr-2"/>Nova reclamação</button>}</header>
  <section className="grid sm:grid-cols-2 xl:grid-cols-5 gap-4 mb-5"><Metrica titulo="Total" valor={metricas.total||0}/><Metrica titulo="Em aberto" valor={metricas.abertas||0} cor="text-amber-600"/><Metrica titulo="Atrasadas" valor={metricas.atrasadas||0} cor="text-red-600"/><Metrica titulo="Concluídas" valor={metricas.concluidas||0} cor="text-emerald-600"/><Metrica titulo="Tempo médio" valor={`${metricas.media_horas||0}h`} cor="text-blue-600"/></section>
  <section className="grid lg:grid-cols-2 xl:grid-cols-3 gap-5 mb-5"><Grafico titulo="Tipos de reclamação"><Barras dados={metricas.por_tipo||[]}/></Grafico><Grafico titulo="Clientes com mais reclamações"><Barras dados={metricas.por_cliente||[]}/></Grafico><Grafico titulo="Por prioridade"><Barras dados={metricas.por_prioridade||[]} prioridade/></Grafico><Grafico titulo="Por líder responsável"><Barras dados={metricas.por_lider||[]}/></Grafico><Grafico titulo="Evolução mensal" classe="xl:col-span-2"><div className="h-56 flex items-end gap-3 border-b border-[var(--border-color)] overflow-x-auto">{(metricas.por_mes||[]).map(x=><div key={x.mes} className="flex-1 min-w-12 text-center"><strong className="text-xs">{x.total}</strong><div className="bg-[#a65526] rounded-t-lg mx-auto min-h-1" style={{height:`${Math.max(4,x.total/maior(metricas.por_mes)*170)}px`}}/><small className="text-[10px] text-[var(--text-muted)]">{x.mes.slice(5)}/{x.mes.slice(2,4)}</small></div>)}</div></Grafico></section>
  {podeRegistrar&&<section className="panel-card"><div className="flex flex-wrap items-center justify-between gap-3 mb-5"><h2 className="section-title">Lista de reclamações</h2><div className="flex gap-2">{[['todos','Todas'],['aberto','Em aberto'],['concluido','Concluídas']].map(([v,n])=><button key={v} onClick={()=>setFiltro(v)} className={`px-3 py-2 rounded-lg text-sm font-bold ${filtro===v?'bg-[var(--primary)] text-white':'bg-[var(--bg-main)]'}`}>{n}</button>)}</div></div><div className="grid xl:grid-cols-2 gap-4">{visiveis.map(r=><Cartao key={r.id} r={r} agora={agora} perfil={perfil} setFoto={setFoto} mudarStatus={mudarStatus} excluir={excluir}/>)}</div>{!visiveis.length&&<p className="text-[var(--text-muted)]">Nenhum registro neste filtro.</p>}</section>}
  {formAberto&&<Formulario form={form} setForm={setForm} catalogos={catalogos} anexar={anexar} salvar={salvar} salvando={salvando} fechar={()=>setFormAberto(false)}/>} {foto&&<div onClick={()=>setFoto(null)} className="fixed inset-0 z-[70] bg-black/85 p-5 grid place-items-center cursor-zoom-out"><button className="absolute top-5 right-5 text-white"><X size={32}/></button><img src={foto.url} alt={foto.nome} className="max-w-[94vw] max-h-[90vh] object-contain !m-0 !rounded-xl"/></div>}</main>;
  return perfil==='leitor'?<div className="min-h-screen bg-[var(--bg-main)]"><LeitorTopbar titulo="Métricas de reclamações"/>{conteudo}</div>:<div className="min-h-screen bg-[var(--bg-main)] flex"><Sidebar/>{conteudo}</div>;
}
function Metrica({titulo,valor,cor=''}){return <div className="metric-card"><BarChart3 className={cor||'text-[var(--primary)]'}/><div><span>{titulo}</span><strong className={cor}>{valor}</strong></div></div>}
function Grafico({titulo,children,classe=''}){return <div className={`panel-card ${classe}`}><h2 className="section-title mb-4">{titulo}</h2>{children}</div>}
function Cartao({r,agora,perfil,setFoto,mudarStatus,excluir}){const p=cores[r.prioridade]||cores.verde,t=restante(r.prazo_em,agora),aberta=r.status==='aberto';return <article className={`rounded-2xl border p-5 ${aberta&&t.atrasado?'border-red-500':'border-[var(--border-color)]'} bg-[var(--bg-card)] shadow-sm`}><div className="flex justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><strong className="text-lg">{r.cliente_nome}</strong><span className="px-2 py-1 rounded-full text-xs font-bold" style={{color:p.cor,background:p.fundo}}>{p.nome}</span>{!aberta&&<span className="px-2 py-1 rounded-full text-xs font-bold bg-emerald-100 text-emerald-700">Concluída</span>}</div><p className="text-sm text-[var(--primary)] font-bold mt-1">{r.tipo_nome}</p></div>{perfil==='administrador'&&<button onClick={()=>excluir(r.id)} className="text-red-600 h-fit"><Trash2 size={18}/></button>}</div><div className={`my-4 p-3 rounded-xl flex items-center gap-3 ${aberta?(t.atrasado?'bg-red-100 text-red-800':'bg-[var(--bg-main)]'):'bg-emerald-50 text-emerald-800'}`}>{aberta?<Clock3 size={20}/>:<CheckCircle2 size={20}/>}<div><strong className="block text-sm">{aberta?(t.atrasado?`Prazo excedido há ${t.texto}`:`Restam ${t.texto}`):'Retorno ao cliente concluído'}</strong><small>{aberta?`Limite: ${new Date(r.prazo_em).toLocaleString('pt-BR')}`:`Concluída em ${new Date(r.concluido_em).toLocaleString('pt-BR')}`}</small></div></div><p className="whitespace-pre-wrap text-sm leading-relaxed">{r.descricao}</p><div className="grid grid-cols-3 sm:grid-cols-4 gap-2 mt-4">{(r.anexos||[]).map((a,i)=>ehImagem(a)?<button key={i} onClick={()=>setFoto(a)} className="relative h-24 rounded-xl overflow-hidden border border-[var(--border-color)]"><img src={a.url} alt={a.nome} className="w-full h-full object-cover !m-0 !rounded-none"/><Image size={15} className="absolute bottom-2 right-2 text-white"/></button>:<a key={i} href={a.url} target="_blank" rel="noreferrer" className="h-24 rounded-xl border border-[var(--border-color)] grid place-items-center text-center text-xs p-2"><Paperclip size={20}/><span>{a.nome}</span></a>)}</div><p className="text-xs text-[var(--text-muted)] mt-4">Líder: {r.lider_nome} · Registrado por {r.criado_por_nome||'Sistema'} em {new Date(r.criado_em).toLocaleString('pt-BR')}</p><button onClick={()=>mudarStatus(r.id,aberta?'concluido':'aberto')} className={`w-full mt-4 p-3 rounded-xl font-bold flex justify-center items-center ${aberta?'bg-emerald-600 text-white':'bg-[var(--bg-main)]'}`}>{aberta?<><CheckCircle2 size={18} className="mr-2"/>Confirmar retorno e concluir</>:<><RotateCcw size={18} className="mr-2"/>Reabrir reclamação</>}</button></article>}
function Formulario({form,setForm,catalogos,anexar,salvar,salvando,fechar}){const prazos=catalogos.prazos||{};return <div className="fixed inset-0 bg-black/60 z-50 grid place-items-center p-4"><form onSubmit={salvar} className="panel-card max-w-3xl w-full max-h-[92vh] overflow-auto"><div className="flex justify-between mb-5"><div><h2 className="text-2xl font-bold">Registrar reclamação</h2><p className="text-sm text-[var(--text-muted)]">A prioridade inicia o prazo automaticamente.</p></div><button type="button" onClick={fechar}>Fechar</button></div><div className="grid sm:grid-cols-2 gap-4"><Selecao titulo="Cliente" valor={form.cliente_id} mudar={v=>setForm({...form,cliente_id:v})} itens={catalogos.clientes}/><Selecao titulo="Tipo de reclamação" valor={form.tipo_id} mudar={v=>setForm({...form,tipo_id:v})} itens={catalogos.tipos}/><label className="font-semibold text-sm sm:col-span-2">Nível de importância<div className="grid sm:grid-cols-3 gap-2 mt-2">{Object.entries(cores).map(([v,p])=><button type="button" key={v} onClick={()=>setForm({...form,prioridade:v})} className={`p-3 rounded-xl border text-left ${form.prioridade===v?'ring-2 ring-offset-2':'opacity-75'}`} style={{borderColor:p.cor,background:p.fundo,color:p.cor}}><strong className="block">{p.nome}</strong><small>Retorno em {formatarPrazo(Number(prazos[`prazo_${v}_min`]||0))}</small></button>)}</div></label><label className="font-semibold text-sm sm:col-span-2">Líder responsável<select required className="field" value={form.lider_responsavel_id} onChange={e=>setForm({...form,lider_responsavel_id:e.target.value})}><option value="">Selecione</option>{catalogos.lideres.map(x=><option key={x.id} value={x.id}>{x.nome}</option>)}</select></label><label className="font-semibold text-sm sm:col-span-2">Descrição<textarea required rows="5" className="field" value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/></label><label className="font-semibold text-sm sm:col-span-2">Fotos e anexos (até 10)<input type="file" multiple className="field" onChange={e=>anexar(e.target.files)}/><div className="flex flex-wrap gap-2 mt-2">{form.anexos.map((a,i)=><span key={i} className="text-xs border rounded-lg p-2">{a.nome}</span>)}</div></label></div><button disabled={salvando} className="w-full mt-5 bg-[var(--primary)] text-white p-3 rounded-xl font-bold">{salvando?'Salvando...':'Salvar e iniciar prazo'}</button></form></div>}
function Selecao({titulo,valor,mudar,itens}){const [texto,setTexto]=useState('');useEffect(()=>{const atual=itens.find(x=>String(x.id)===String(valor));if(atual&&atual.nome!==texto)setTexto(atual.nome);if(!valor&&itens.some(x=>x.nome===texto))setTexto('');},[valor,itens]);const lista=`opcoes-${titulo.replace(/\W/g,'-')}`;return <label className="font-semibold text-sm">{titulo}<input required list={lista} className="field" placeholder="Digite para pesquisar" value={texto} onChange={e=>{const digitado=e.target.value;setTexto(digitado);const achado=itens.find(x=>x.nome.toLocaleLowerCase('pt-BR')===digitado.toLocaleLowerCase('pt-BR'));mudar(achado?String(achado.id):'');}}/><datalist id={lista}>{itens.map(x=><option key={x.id} value={x.nome}/>)}</datalist></label>}
